const {User, OrderDetail} = require("../database/index")

const users = [{
    "email": "kgabotti0@mashable.com",
    "first_name": "Karol",
    "last_name": "Gabotti",
    "access_level": true,
    "phone": "4953815438"
  }, {
    "email": "pastlet1@de.vu",
    "first_name": "Perle",
    "last_name": "Astlet",
    "access_level": false,
    "phone": "9554042886"
  }, {
    "email": "bcoulman2@hibu.com",
    "first_name": "Berty",
    "last_name": "Coulman",
    "access_level": false,
    "phone": "1001900828"
  }, {
    "email": "dlowrance3@hatena.ne.jp",
    "first_name": "Dido",
    "last_name": "Lowrance",
    "access_level": false,
    "phone": "9604882342"
  }, {
    "email": "npighills4@marriott.com",
    "first_name": "Nicholle",
    "last_name": "Pighills",
    "access_level": true,
    "phone": "3372058262"
  }, {
    "email": "fmitkin5@washingtonpost.com",
    "first_name": "Fayina",
    "last_name": "Mitkin",
    "access_level": false,
    "phone": "4027496288"
  }, {
    "email": "saxtens6@rakuten.co.jp",
    "first_name": "Selie",
    "last_name": "Axtens",
    "access_level": false,
    "phone": "4996195460"
  }, {
    "email": "cmasedon7@lycos.com",
    "first_name": "Colan",
    "last_name": "Masedon",
    "access_level": true,
    "phone": "2439553281"
  }, {
    "email": "glockley8@howstuffworks.com",
    "first_name": "Garrek",
    "last_name": "Lockley",
    "access_level": false,
    "phone": "1301224276"
  }, {
    "email": "vberringer9@cargocollective.com",
    "first_name": "Venus",
    "last_name": "Berringer",
    "access_level": true,
    "phone": "2417360348"
  }, {
    "email": "nmckanea@microsoft.com",
    "first_name": "Nap",
    "last_name": "McKane",
    "access_level": true,
    "phone": "3849778387"
  }, {
    "email": "lfountianb@dropbox.com",
    "first_name": "Lenee",
    "last_name": "Fountian",
    "access_level": false,
    "phone": "9962693216"
  }, {
    "email": "pglayzerc@reuters.com",
    "first_name": "Philippa",
    "last_name": "Glayzer",
    "access_level": true,
    "phone": "3959791508"
  }, {
    "email": "chaggartd@barnesandnoble.com",
    "first_name": "Curran",
    "last_name": "Haggart",
    "access_level": false,
    "phone": "6845134422"
  }, {
    "email": "lgarriee@sitemeter.com",
    "first_name": "Lydie",
    "last_name": "Garrie",
    "access_level": true,
    "phone": "8275833913"
  }, {
    "email": "dfollitf@storify.com",
    "first_name": "Doralin",
    "last_name": "Follit",
    "access_level": true,
    "phone": "8135702757"
  }, {
    "email": "fjerremsg@mapquest.com",
    "first_name": "Forrester",
    "last_name": "Jerrems",
    "access_level": true,
    "phone": "8265220857"
  }, {
    "email": "lhartleh@t-online.de",
    "first_name": "Lara",
    "last_name": "Hartle",
    "access_level": false,
    "phone": "6564599770"
  }, {
    "email": "iduseyi@comcast.net",
    "first_name": "Irma",
    "last_name": "Dusey",
    "access_level": false,
    "phone": "8529108729"
  }, {
    "email": "cmayorj@sphinn.com",
    "first_name": "Charo",
    "last_name": "Mayor",
    "access_level": true,
    "phone": "6244030715"
  }, {
    "email": "rkeek@loc.gov",
    "first_name": "Ruby",
    "last_name": "Kee",
    "access_level": true,
    "phone": "3369542989"
  }, {
    "email": "scanetel@ezinearticles.com",
    "first_name": "Saw",
    "last_name": "Canete",
    "access_level": false,
    "phone": "2039687837"
  }, {
    "email": "ghullyerm@eepurl.com",
    "first_name": "Gary",
    "last_name": "Hullyer",
    "access_level": false,
    "phone": "1951593204"
  }, {
    "email": "rloodyn@stumbleupon.com",
    "first_name": "Rosalinda",
    "last_name": "Loody",
    "access_level": false,
    "phone": "1443268302"
  }, {
    "email": "tbroadbereo@ifeng.com",
    "first_name": "Trey",
    "last_name": "Broadbere",
    "access_level": false,
    "phone": "3575672452"
  }, {
    "email": "fcicerop@google.nl",
    "first_name": "Fayina",
    "last_name": "Cicero",
    "access_level": true,
    "phone": "2344389124"
  }, {
    "email": "nbillettq@scientificamerican.com",
    "first_name": "Nehemiah",
    "last_name": "Billett",
    "access_level": false,
    "phone": "6664905491"
  }, {
    "email": "mbrafieldr@youku.com",
    "first_name": "Mirella",
    "last_name": "Brafield",
    "access_level": false,
    "phone": "6517169188"
  }, {
    "email": "lblannins@accuweather.com",
    "first_name": "Libbie",
    "last_name": "Blannin",
    "access_level": true,
    "phone": "7238492268"
  }, {
    "email": "dsyalvestert@icio.us",
    "first_name": "Danie",
    "last_name": "Syalvester",
    "access_level": false,
    "phone": "8066306937"
  }, {
    "email": "galiboneu@google.com.au",
    "first_name": "Gabriel",
    "last_name": "Alibone",
    "access_level": false,
    "phone": "3258181918"
  }, {
    "email": "afilkovv@odnoklassniki.ru",
    "first_name": "Arlen",
    "last_name": "Filkov",
    "access_level": true,
    "phone": "2663776684"
  }, {
    "email": "lcastendaw@webmd.com",
    "first_name": "Layla",
    "last_name": "Castenda",
    "access_level": false,
    "phone": "3144621172"
  }, {
    "email": "lduddlex@fotki.com",
    "first_name": "Lenna",
    "last_name": "Duddle",
    "access_level": true,
    "phone": "8607528962"
  }, {
    "email": "jgilbeey@ebay.com",
    "first_name": "Jethro",
    "last_name": "Gilbee",
    "access_level": true,
    "phone": "3483034926"
  }, {
    "email": "pfilipsonz@feedburner.com",
    "first_name": "Pru",
    "last_name": "Filipson",
    "access_level": true,
    "phone": "1387785814"
  }, {
    "email": "pnelius10@topsy.com",
    "first_name": "Paulo",
    "last_name": "Nelius",
    "access_level": true,
    "phone": "6045070875"
  }, {
    "email": "lgeorg11@canalblog.com",
    "first_name": "Lolly",
    "last_name": "Georg",
    "access_level": true,
    "phone": "5892145429"
  }, {
    "email": "kventom12@unesco.org",
    "first_name": "King",
    "last_name": "Ventom",
    "access_level": false,
    "phone": "6543668568"
  }, {
    "email": "fmannie13@google.ca",
    "first_name": "Fancy",
    "last_name": "Mannie",
    "access_level": false,
    "phone": "1366074495"
  }, {
    "email": "wmackereth14@cornell.edu",
    "first_name": "Wynn",
    "last_name": "MacKereth",
    "access_level": false,
    "phone": "7015259972"
  }, {
    "email": "khealey15@usa.gov",
    "first_name": "Koenraad",
    "last_name": "Healey",
    "access_level": false,
    "phone": "7126612311"
  }, {
    "email": "ffilippucci16@godaddy.com",
    "first_name": "Fonz",
    "last_name": "Filippucci",
    "access_level": true,
    "phone": "4712091970"
  }, {
    "email": "mlinley17@amazon.de",
    "first_name": "Melantha",
    "last_name": "Linley",
    "access_level": true,
    "phone": "4736533712"
  }, {
    "email": "dbollard18@miibeian.gov.cn",
    "first_name": "Daven",
    "last_name": "Bollard",
    "access_level": true,
    "phone": "3241623473"
  }, {
    "email": "mfishlock19@bigcartel.com",
    "first_name": "Maxim",
    "last_name": "Fishlock",
    "access_level": true,
    "phone": "9633410601"
  }, {
    "email": "rsimkovich1a@geocities.jp",
    "first_name": "Rozanne",
    "last_name": "Simkovich",
    "access_level": false,
    "phone": "1432160451"
  }, {
    "email": "mapple1b@clickbank.net",
    "first_name": "Mattias",
    "last_name": "Apple",
    "access_level": false,
    "phone": "3309299968"
  }, {
    "email": "rizzett1c@chron.com",
    "first_name": "Rodolphe",
    "last_name": "Izzett",
    "access_level": false,
    "phone": "3033590587"
  }, {
    "email": "kjon1d@techcrunch.com",
    "first_name": "Krissy",
    "last_name": "Jon",
    "access_level": true,
    "phone": "7038826589"
  }]

  async function loadMockUsers(){

    try {
  
      await User.bulkCreate(users, {
        include: [{
          model: OrderDetail,
        }],
      })
  
     console.log("Users loaded to DB")
  
    } catch (error) {
      console.log(error)
    }
  }

module.exports={
  loadMockUsers
}
